version: '2.6'

services:
  postgres_db:
    container_name: 'redditdb'
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: 'redditdb'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - "${PWD}/local_database:/var/lib/postgres/data"

  mysql_db:
    container_name: 'mysqldb'
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'reddit-test-db'
      MYSQL_USER: 'testuser'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "${PWD}/local_db:/var/lib/mysql"


volumes:
  local_database:
