version: '2.6'

services:
  db:
    container_name: 'redditdb'
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'redditdb'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "${PWD}/my_db:/var/lib/mysql"

volumes:
  my_db:
